//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gql.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IgqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gqlParser.selectItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectItem([NotNull] gqlParser.SelectItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gqlParser.selectItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectItem([NotNull] gqlParser.SelectItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gqlParser.querySpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuerySpecification([NotNull] gqlParser.QuerySpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gqlParser.querySpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuerySpecification([NotNull] gqlParser.QuerySpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gqlParser.setQuantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetQuantifier([NotNull] gqlParser.SetQuantifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gqlParser.setQuantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetQuantifier([NotNull] gqlParser.SetQuantifierContext context);
}
